server:
  port: 8002
  context-path: /investors
spring:
  devtools:
    restart:
      additional-paths: datalayer/investors/src/main/java
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          connection:
            autocommit: true
  rabbitmq:
    port: 5672
    host: 10.0.0.38
    username: yuyidi
    password: yuyidi
