// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FuturesQuoteData.proto

package com.waben.stock.futuresgateway.yisheng.common.protobuf;

public final class FuturesQuoteData {
  private FuturesQuoteData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FuturesQuoteDataBaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FuturesQuoteDataBase)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .CommandType cmd = 1;</code>
     */
    boolean hasCmd();
    /**
     * <code>required .CommandType cmd = 1;</code>
     */
    com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType getCmd();

    /**
     * <code>optional string time = 2;</code>
     */
    boolean hasTime();
    /**
     * <code>optional string time = 2;</code>
     */
    java.lang.String getTime();
    /**
     * <code>optional string time = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>optional string commodityNo = 3;</code>
     */
    boolean hasCommodityNo();
    /**
     * <code>optional string commodityNo = 3;</code>
     */
    java.lang.String getCommodityNo();
    /**
     * <code>optional string commodityNo = 3;</code>
     */
    com.google.protobuf.ByteString
        getCommodityNoBytes();

    /**
     * <code>optional string contractNo = 4;</code>
     */
    boolean hasContractNo();
    /**
     * <code>optional string contractNo = 4;</code>
     */
    java.lang.String getContractNo();
    /**
     * <code>optional string contractNo = 4;</code>
     */
    com.google.protobuf.ByteString
        getContractNoBytes();

    /**
     * <code>optional string bidPrice = 5;</code>
     */
    boolean hasBidPrice();
    /**
     * <code>optional string bidPrice = 5;</code>
     */
    java.lang.String getBidPrice();
    /**
     * <code>optional string bidPrice = 5;</code>
     */
    com.google.protobuf.ByteString
        getBidPriceBytes();

    /**
     * <code>optional int64 bidSize = 6;</code>
     */
    boolean hasBidSize();
    /**
     * <code>optional int64 bidSize = 6;</code>
     */
    long getBidSize();

    /**
     * <code>optional string askPrice = 7;</code>
     */
    boolean hasAskPrice();
    /**
     * <code>optional string askPrice = 7;</code>
     */
    java.lang.String getAskPrice();
    /**
     * <code>optional string askPrice = 7;</code>
     */
    com.google.protobuf.ByteString
        getAskPriceBytes();

    /**
     * <code>optional int64 askSize = 8;</code>
     */
    boolean hasAskSize();
    /**
     * <code>optional int64 askSize = 8;</code>
     */
    long getAskSize();

    /**
     * <code>optional string lastPrice = 9;</code>
     */
    boolean hasLastPrice();
    /**
     * <code>optional string lastPrice = 9;</code>
     */
    java.lang.String getLastPrice();
    /**
     * <code>optional string lastPrice = 9;</code>
     */
    com.google.protobuf.ByteString
        getLastPriceBytes();

    /**
     * <code>optional int64 lastSize = 10;</code>
     */
    boolean hasLastSize();
    /**
     * <code>optional int64 lastSize = 10;</code>
     */
    long getLastSize();

    /**
     * <code>optional string openPrice = 11;</code>
     */
    boolean hasOpenPrice();
    /**
     * <code>optional string openPrice = 11;</code>
     */
    java.lang.String getOpenPrice();
    /**
     * <code>optional string openPrice = 11;</code>
     */
    com.google.protobuf.ByteString
        getOpenPriceBytes();

    /**
     * <code>optional string highPrice = 12;</code>
     */
    boolean hasHighPrice();
    /**
     * <code>optional string highPrice = 12;</code>
     */
    java.lang.String getHighPrice();
    /**
     * <code>optional string highPrice = 12;</code>
     */
    com.google.protobuf.ByteString
        getHighPriceBytes();

    /**
     * <code>optional string lowPrice = 13;</code>
     */
    boolean hasLowPrice();
    /**
     * <code>optional string lowPrice = 13;</code>
     */
    java.lang.String getLowPrice();
    /**
     * <code>optional string lowPrice = 13;</code>
     */
    com.google.protobuf.ByteString
        getLowPriceBytes();

    /**
     * <code>optional string closePrice = 14;</code>
     */
    boolean hasClosePrice();
    /**
     * <code>optional string closePrice = 14;</code>
     */
    java.lang.String getClosePrice();
    /**
     * <code>optional string closePrice = 14;</code>
     */
    com.google.protobuf.ByteString
        getClosePriceBytes();

    /**
     * <code>optional int64 volume = 15;</code>
     */
    boolean hasVolume();
    /**
     * <code>optional int64 volume = 15;</code>
     */
    long getVolume();

    /**
     * <code>optional int64 totalVolume = 16;</code>
     */
    boolean hasTotalVolume();
    /**
     * <code>optional int64 totalVolume = 16;</code>
     */
    long getTotalVolume();
  }
  /**
   * Protobuf type {@code FuturesQuoteDataBase}
   */
  public  static final class FuturesQuoteDataBase extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FuturesQuoteDataBase)
      FuturesQuoteDataBaseOrBuilder {
    // Use FuturesQuoteDataBase.newBuilder() to construct.
    private FuturesQuoteDataBase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FuturesQuoteDataBase() {
      cmd_ = 1;
      time_ = "";
      commodityNo_ = "";
      contractNo_ = "";
      bidPrice_ = "";
      bidSize_ = 0L;
      askPrice_ = "";
      askSize_ = 0L;
      lastPrice_ = "";
      lastSize_ = 0L;
      openPrice_ = "";
      highPrice_ = "";
      lowPrice_ = "";
      closePrice_ = "";
      volume_ = 0L;
      totalVolume_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FuturesQuoteDataBase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType value = com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                cmd_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              time_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              commodityNo_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              contractNo_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              bidPrice_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              bidSize_ = input.readInt64();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              askPrice_ = bs;
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              askSize_ = input.readInt64();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              lastPrice_ = bs;
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              lastSize_ = input.readInt64();
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              openPrice_ = bs;
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              highPrice_ = bs;
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00001000;
              lowPrice_ = bs;
              break;
            }
            case 114: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00002000;
              closePrice_ = bs;
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              volume_ = input.readInt64();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              totalVolume_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.internal_static_FuturesQuoteDataBase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.internal_static_FuturesQuoteDataBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.class, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.Builder.class);
    }

    private int bitField0_;
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>required .CommandType cmd = 1;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .CommandType cmd = 1;</code>
     */
    public com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType getCmd() {
      com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType result = com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType.valueOf(cmd_);
      return result == null ? com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType.AUTH : result;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private volatile java.lang.Object time_;
    /**
     * <code>optional string time = 2;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string time = 2;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string time = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMODITYNO_FIELD_NUMBER = 3;
    private volatile java.lang.Object commodityNo_;
    /**
     * <code>optional string commodityNo = 3;</code>
     */
    public boolean hasCommodityNo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string commodityNo = 3;</code>
     */
    public java.lang.String getCommodityNo() {
      java.lang.Object ref = commodityNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          commodityNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string commodityNo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCommodityNoBytes() {
      java.lang.Object ref = commodityNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commodityNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTRACTNO_FIELD_NUMBER = 4;
    private volatile java.lang.Object contractNo_;
    /**
     * <code>optional string contractNo = 4;</code>
     */
    public boolean hasContractNo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string contractNo = 4;</code>
     */
    public java.lang.String getContractNo() {
      java.lang.Object ref = contractNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contractNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string contractNo = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContractNoBytes() {
      java.lang.Object ref = contractNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIDPRICE_FIELD_NUMBER = 5;
    private volatile java.lang.Object bidPrice_;
    /**
     * <code>optional string bidPrice = 5;</code>
     */
    public boolean hasBidPrice() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string bidPrice = 5;</code>
     */
    public java.lang.String getBidPrice() {
      java.lang.Object ref = bidPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bidPrice_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string bidPrice = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBidPriceBytes() {
      java.lang.Object ref = bidPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bidPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIDSIZE_FIELD_NUMBER = 6;
    private long bidSize_;
    /**
     * <code>optional int64 bidSize = 6;</code>
     */
    public boolean hasBidSize() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 bidSize = 6;</code>
     */
    public long getBidSize() {
      return bidSize_;
    }

    public static final int ASKPRICE_FIELD_NUMBER = 7;
    private volatile java.lang.Object askPrice_;
    /**
     * <code>optional string askPrice = 7;</code>
     */
    public boolean hasAskPrice() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string askPrice = 7;</code>
     */
    public java.lang.String getAskPrice() {
      java.lang.Object ref = askPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          askPrice_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string askPrice = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAskPriceBytes() {
      java.lang.Object ref = askPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        askPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASKSIZE_FIELD_NUMBER = 8;
    private long askSize_;
    /**
     * <code>optional int64 askSize = 8;</code>
     */
    public boolean hasAskSize() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 askSize = 8;</code>
     */
    public long getAskSize() {
      return askSize_;
    }

    public static final int LASTPRICE_FIELD_NUMBER = 9;
    private volatile java.lang.Object lastPrice_;
    /**
     * <code>optional string lastPrice = 9;</code>
     */
    public boolean hasLastPrice() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string lastPrice = 9;</code>
     */
    public java.lang.String getLastPrice() {
      java.lang.Object ref = lastPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastPrice_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lastPrice = 9;</code>
     */
    public com.google.protobuf.ByteString
        getLastPriceBytes() {
      java.lang.Object ref = lastPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTSIZE_FIELD_NUMBER = 10;
    private long lastSize_;
    /**
     * <code>optional int64 lastSize = 10;</code>
     */
    public boolean hasLastSize() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int64 lastSize = 10;</code>
     */
    public long getLastSize() {
      return lastSize_;
    }

    public static final int OPENPRICE_FIELD_NUMBER = 11;
    private volatile java.lang.Object openPrice_;
    /**
     * <code>optional string openPrice = 11;</code>
     */
    public boolean hasOpenPrice() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string openPrice = 11;</code>
     */
    public java.lang.String getOpenPrice() {
      java.lang.Object ref = openPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          openPrice_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string openPrice = 11;</code>
     */
    public com.google.protobuf.ByteString
        getOpenPriceBytes() {
      java.lang.Object ref = openPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        openPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HIGHPRICE_FIELD_NUMBER = 12;
    private volatile java.lang.Object highPrice_;
    /**
     * <code>optional string highPrice = 12;</code>
     */
    public boolean hasHighPrice() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string highPrice = 12;</code>
     */
    public java.lang.String getHighPrice() {
      java.lang.Object ref = highPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          highPrice_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string highPrice = 12;</code>
     */
    public com.google.protobuf.ByteString
        getHighPriceBytes() {
      java.lang.Object ref = highPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        highPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOWPRICE_FIELD_NUMBER = 13;
    private volatile java.lang.Object lowPrice_;
    /**
     * <code>optional string lowPrice = 13;</code>
     */
    public boolean hasLowPrice() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string lowPrice = 13;</code>
     */
    public java.lang.String getLowPrice() {
      java.lang.Object ref = lowPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lowPrice_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lowPrice = 13;</code>
     */
    public com.google.protobuf.ByteString
        getLowPriceBytes() {
      java.lang.Object ref = lowPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lowPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLOSEPRICE_FIELD_NUMBER = 14;
    private volatile java.lang.Object closePrice_;
    /**
     * <code>optional string closePrice = 14;</code>
     */
    public boolean hasClosePrice() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional string closePrice = 14;</code>
     */
    public java.lang.String getClosePrice() {
      java.lang.Object ref = closePrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          closePrice_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string closePrice = 14;</code>
     */
    public com.google.protobuf.ByteString
        getClosePriceBytes() {
      java.lang.Object ref = closePrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        closePrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VOLUME_FIELD_NUMBER = 15;
    private long volume_;
    /**
     * <code>optional int64 volume = 15;</code>
     */
    public boolean hasVolume() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int64 volume = 15;</code>
     */
    public long getVolume() {
      return volume_;
    }

    public static final int TOTALVOLUME_FIELD_NUMBER = 16;
    private long totalVolume_;
    /**
     * <code>optional int64 totalVolume = 16;</code>
     */
    public boolean hasTotalVolume() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional int64 totalVolume = 16;</code>
     */
    public long getTotalVolume() {
      return totalVolume_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, commodityNo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, contractNo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, bidPrice_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, bidSize_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, askPrice_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, askSize_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, lastPrice_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, lastSize_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, openPrice_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, highPrice_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, lowPrice_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, closePrice_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt64(15, volume_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt64(16, totalVolume_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, commodityNo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, contractNo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, bidPrice_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, bidSize_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, askPrice_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, askSize_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, lastPrice_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, lastSize_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, openPrice_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, highPrice_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, lowPrice_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, closePrice_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(15, volume_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(16, totalVolume_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase)) {
        return super.equals(obj);
      }
      com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase other = (com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase) obj;

      boolean result = true;
      result = result && (hasCmd() == other.hasCmd());
      if (hasCmd()) {
        result = result && cmd_ == other.cmd_;
      }
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && getTime()
            .equals(other.getTime());
      }
      result = result && (hasCommodityNo() == other.hasCommodityNo());
      if (hasCommodityNo()) {
        result = result && getCommodityNo()
            .equals(other.getCommodityNo());
      }
      result = result && (hasContractNo() == other.hasContractNo());
      if (hasContractNo()) {
        result = result && getContractNo()
            .equals(other.getContractNo());
      }
      result = result && (hasBidPrice() == other.hasBidPrice());
      if (hasBidPrice()) {
        result = result && getBidPrice()
            .equals(other.getBidPrice());
      }
      result = result && (hasBidSize() == other.hasBidSize());
      if (hasBidSize()) {
        result = result && (getBidSize()
            == other.getBidSize());
      }
      result = result && (hasAskPrice() == other.hasAskPrice());
      if (hasAskPrice()) {
        result = result && getAskPrice()
            .equals(other.getAskPrice());
      }
      result = result && (hasAskSize() == other.hasAskSize());
      if (hasAskSize()) {
        result = result && (getAskSize()
            == other.getAskSize());
      }
      result = result && (hasLastPrice() == other.hasLastPrice());
      if (hasLastPrice()) {
        result = result && getLastPrice()
            .equals(other.getLastPrice());
      }
      result = result && (hasLastSize() == other.hasLastSize());
      if (hasLastSize()) {
        result = result && (getLastSize()
            == other.getLastSize());
      }
      result = result && (hasOpenPrice() == other.hasOpenPrice());
      if (hasOpenPrice()) {
        result = result && getOpenPrice()
            .equals(other.getOpenPrice());
      }
      result = result && (hasHighPrice() == other.hasHighPrice());
      if (hasHighPrice()) {
        result = result && getHighPrice()
            .equals(other.getHighPrice());
      }
      result = result && (hasLowPrice() == other.hasLowPrice());
      if (hasLowPrice()) {
        result = result && getLowPrice()
            .equals(other.getLowPrice());
      }
      result = result && (hasClosePrice() == other.hasClosePrice());
      if (hasClosePrice()) {
        result = result && getClosePrice()
            .equals(other.getClosePrice());
      }
      result = result && (hasVolume() == other.hasVolume());
      if (hasVolume()) {
        result = result && (getVolume()
            == other.getVolume());
      }
      result = result && (hasTotalVolume() == other.hasTotalVolume());
      if (hasTotalVolume()) {
        result = result && (getTotalVolume()
            == other.getTotalVolume());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCmd()) {
        hash = (37 * hash) + CMD_FIELD_NUMBER;
        hash = (53 * hash) + cmd_;
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      if (hasCommodityNo()) {
        hash = (37 * hash) + COMMODITYNO_FIELD_NUMBER;
        hash = (53 * hash) + getCommodityNo().hashCode();
      }
      if (hasContractNo()) {
        hash = (37 * hash) + CONTRACTNO_FIELD_NUMBER;
        hash = (53 * hash) + getContractNo().hashCode();
      }
      if (hasBidPrice()) {
        hash = (37 * hash) + BIDPRICE_FIELD_NUMBER;
        hash = (53 * hash) + getBidPrice().hashCode();
      }
      if (hasBidSize()) {
        hash = (37 * hash) + BIDSIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getBidSize());
      }
      if (hasAskPrice()) {
        hash = (37 * hash) + ASKPRICE_FIELD_NUMBER;
        hash = (53 * hash) + getAskPrice().hashCode();
      }
      if (hasAskSize()) {
        hash = (37 * hash) + ASKSIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAskSize());
      }
      if (hasLastPrice()) {
        hash = (37 * hash) + LASTPRICE_FIELD_NUMBER;
        hash = (53 * hash) + getLastPrice().hashCode();
      }
      if (hasLastSize()) {
        hash = (37 * hash) + LASTSIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLastSize());
      }
      if (hasOpenPrice()) {
        hash = (37 * hash) + OPENPRICE_FIELD_NUMBER;
        hash = (53 * hash) + getOpenPrice().hashCode();
      }
      if (hasHighPrice()) {
        hash = (37 * hash) + HIGHPRICE_FIELD_NUMBER;
        hash = (53 * hash) + getHighPrice().hashCode();
      }
      if (hasLowPrice()) {
        hash = (37 * hash) + LOWPRICE_FIELD_NUMBER;
        hash = (53 * hash) + getLowPrice().hashCode();
      }
      if (hasClosePrice()) {
        hash = (37 * hash) + CLOSEPRICE_FIELD_NUMBER;
        hash = (53 * hash) + getClosePrice().hashCode();
      }
      if (hasVolume()) {
        hash = (37 * hash) + VOLUME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getVolume());
      }
      if (hasTotalVolume()) {
        hash = (37 * hash) + TOTALVOLUME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTotalVolume());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FuturesQuoteDataBase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FuturesQuoteDataBase)
        com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.internal_static_FuturesQuoteDataBase_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.internal_static_FuturesQuoteDataBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.class, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.Builder.class);
      }

      // Construct using com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmd_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        commodityNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        contractNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        bidPrice_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        bidSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        askPrice_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        askSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        lastPrice_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        lastSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        openPrice_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        highPrice_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        lowPrice_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        closePrice_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        volume_ = 0L;
        bitField0_ = (bitField0_ & ~0x00004000);
        totalVolume_ = 0L;
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.internal_static_FuturesQuoteDataBase_descriptor;
      }

      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase getDefaultInstanceForType() {
        return com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.getDefaultInstance();
      }

      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase build() {
        com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase buildPartial() {
        com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase result = new com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.commodityNo_ = commodityNo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.contractNo_ = contractNo_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.bidPrice_ = bidPrice_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.bidSize_ = bidSize_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.askPrice_ = askPrice_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.askSize_ = askSize_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.lastPrice_ = lastPrice_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.lastSize_ = lastSize_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.openPrice_ = openPrice_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.highPrice_ = highPrice_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.lowPrice_ = lowPrice_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.closePrice_ = closePrice_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.volume_ = volume_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.totalVolume_ = totalVolume_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase) {
          return mergeFrom((com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase other) {
        if (other == com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000002;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasCommodityNo()) {
          bitField0_ |= 0x00000004;
          commodityNo_ = other.commodityNo_;
          onChanged();
        }
        if (other.hasContractNo()) {
          bitField0_ |= 0x00000008;
          contractNo_ = other.contractNo_;
          onChanged();
        }
        if (other.hasBidPrice()) {
          bitField0_ |= 0x00000010;
          bidPrice_ = other.bidPrice_;
          onChanged();
        }
        if (other.hasBidSize()) {
          setBidSize(other.getBidSize());
        }
        if (other.hasAskPrice()) {
          bitField0_ |= 0x00000040;
          askPrice_ = other.askPrice_;
          onChanged();
        }
        if (other.hasAskSize()) {
          setAskSize(other.getAskSize());
        }
        if (other.hasLastPrice()) {
          bitField0_ |= 0x00000100;
          lastPrice_ = other.lastPrice_;
          onChanged();
        }
        if (other.hasLastSize()) {
          setLastSize(other.getLastSize());
        }
        if (other.hasOpenPrice()) {
          bitField0_ |= 0x00000400;
          openPrice_ = other.openPrice_;
          onChanged();
        }
        if (other.hasHighPrice()) {
          bitField0_ |= 0x00000800;
          highPrice_ = other.highPrice_;
          onChanged();
        }
        if (other.hasLowPrice()) {
          bitField0_ |= 0x00001000;
          lowPrice_ = other.lowPrice_;
          onChanged();
        }
        if (other.hasClosePrice()) {
          bitField0_ |= 0x00002000;
          closePrice_ = other.closePrice_;
          onChanged();
        }
        if (other.hasVolume()) {
          setVolume(other.getVolume());
        }
        if (other.hasTotalVolume()) {
          setTotalVolume(other.getTotalVolume());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmd()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int cmd_ = 1;
      /**
       * <code>required .CommandType cmd = 1;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .CommandType cmd = 1;</code>
       */
      public com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType getCmd() {
        com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType result = com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType.valueOf(cmd_);
        return result == null ? com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType.AUTH : result;
      }
      /**
       * <code>required .CommandType cmd = 1;</code>
       */
      public Builder setCmd(com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .CommandType cmd = 1;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>optional string time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string time = 2;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            time_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string time = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string time = 2;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string time = 2;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string time = 2;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object commodityNo_ = "";
      /**
       * <code>optional string commodityNo = 3;</code>
       */
      public boolean hasCommodityNo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string commodityNo = 3;</code>
       */
      public java.lang.String getCommodityNo() {
        java.lang.Object ref = commodityNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            commodityNo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string commodityNo = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCommodityNoBytes() {
        java.lang.Object ref = commodityNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commodityNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string commodityNo = 3;</code>
       */
      public Builder setCommodityNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        commodityNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string commodityNo = 3;</code>
       */
      public Builder clearCommodityNo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        commodityNo_ = getDefaultInstance().getCommodityNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string commodityNo = 3;</code>
       */
      public Builder setCommodityNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        commodityNo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contractNo_ = "";
      /**
       * <code>optional string contractNo = 4;</code>
       */
      public boolean hasContractNo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string contractNo = 4;</code>
       */
      public java.lang.String getContractNo() {
        java.lang.Object ref = contractNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            contractNo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contractNo = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContractNoBytes() {
        java.lang.Object ref = contractNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contractNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contractNo = 4;</code>
       */
      public Builder setContractNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        contractNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contractNo = 4;</code>
       */
      public Builder clearContractNo() {
        bitField0_ = (bitField0_ & ~0x00000008);
        contractNo_ = getDefaultInstance().getContractNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string contractNo = 4;</code>
       */
      public Builder setContractNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        contractNo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bidPrice_ = "";
      /**
       * <code>optional string bidPrice = 5;</code>
       */
      public boolean hasBidPrice() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string bidPrice = 5;</code>
       */
      public java.lang.String getBidPrice() {
        java.lang.Object ref = bidPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bidPrice_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bidPrice = 5;</code>
       */
      public com.google.protobuf.ByteString
          getBidPriceBytes() {
        java.lang.Object ref = bidPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bidPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bidPrice = 5;</code>
       */
      public Builder setBidPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        bidPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bidPrice = 5;</code>
       */
      public Builder clearBidPrice() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bidPrice_ = getDefaultInstance().getBidPrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string bidPrice = 5;</code>
       */
      public Builder setBidPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        bidPrice_ = value;
        onChanged();
        return this;
      }

      private long bidSize_ ;
      /**
       * <code>optional int64 bidSize = 6;</code>
       */
      public boolean hasBidSize() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 bidSize = 6;</code>
       */
      public long getBidSize() {
        return bidSize_;
      }
      /**
       * <code>optional int64 bidSize = 6;</code>
       */
      public Builder setBidSize(long value) {
        bitField0_ |= 0x00000020;
        bidSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 bidSize = 6;</code>
       */
      public Builder clearBidSize() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bidSize_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object askPrice_ = "";
      /**
       * <code>optional string askPrice = 7;</code>
       */
      public boolean hasAskPrice() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string askPrice = 7;</code>
       */
      public java.lang.String getAskPrice() {
        java.lang.Object ref = askPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            askPrice_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string askPrice = 7;</code>
       */
      public com.google.protobuf.ByteString
          getAskPriceBytes() {
        java.lang.Object ref = askPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          askPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string askPrice = 7;</code>
       */
      public Builder setAskPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        askPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string askPrice = 7;</code>
       */
      public Builder clearAskPrice() {
        bitField0_ = (bitField0_ & ~0x00000040);
        askPrice_ = getDefaultInstance().getAskPrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string askPrice = 7;</code>
       */
      public Builder setAskPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        askPrice_ = value;
        onChanged();
        return this;
      }

      private long askSize_ ;
      /**
       * <code>optional int64 askSize = 8;</code>
       */
      public boolean hasAskSize() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 askSize = 8;</code>
       */
      public long getAskSize() {
        return askSize_;
      }
      /**
       * <code>optional int64 askSize = 8;</code>
       */
      public Builder setAskSize(long value) {
        bitField0_ |= 0x00000080;
        askSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 askSize = 8;</code>
       */
      public Builder clearAskSize() {
        bitField0_ = (bitField0_ & ~0x00000080);
        askSize_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object lastPrice_ = "";
      /**
       * <code>optional string lastPrice = 9;</code>
       */
      public boolean hasLastPrice() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string lastPrice = 9;</code>
       */
      public java.lang.String getLastPrice() {
        java.lang.Object ref = lastPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastPrice_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lastPrice = 9;</code>
       */
      public com.google.protobuf.ByteString
          getLastPriceBytes() {
        java.lang.Object ref = lastPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lastPrice = 9;</code>
       */
      public Builder setLastPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        lastPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastPrice = 9;</code>
       */
      public Builder clearLastPrice() {
        bitField0_ = (bitField0_ & ~0x00000100);
        lastPrice_ = getDefaultInstance().getLastPrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastPrice = 9;</code>
       */
      public Builder setLastPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        lastPrice_ = value;
        onChanged();
        return this;
      }

      private long lastSize_ ;
      /**
       * <code>optional int64 lastSize = 10;</code>
       */
      public boolean hasLastSize() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 lastSize = 10;</code>
       */
      public long getLastSize() {
        return lastSize_;
      }
      /**
       * <code>optional int64 lastSize = 10;</code>
       */
      public Builder setLastSize(long value) {
        bitField0_ |= 0x00000200;
        lastSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 lastSize = 10;</code>
       */
      public Builder clearLastSize() {
        bitField0_ = (bitField0_ & ~0x00000200);
        lastSize_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object openPrice_ = "";
      /**
       * <code>optional string openPrice = 11;</code>
       */
      public boolean hasOpenPrice() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string openPrice = 11;</code>
       */
      public java.lang.String getOpenPrice() {
        java.lang.Object ref = openPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            openPrice_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string openPrice = 11;</code>
       */
      public com.google.protobuf.ByteString
          getOpenPriceBytes() {
        java.lang.Object ref = openPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          openPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string openPrice = 11;</code>
       */
      public Builder setOpenPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        openPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string openPrice = 11;</code>
       */
      public Builder clearOpenPrice() {
        bitField0_ = (bitField0_ & ~0x00000400);
        openPrice_ = getDefaultInstance().getOpenPrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string openPrice = 11;</code>
       */
      public Builder setOpenPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        openPrice_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object highPrice_ = "";
      /**
       * <code>optional string highPrice = 12;</code>
       */
      public boolean hasHighPrice() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string highPrice = 12;</code>
       */
      public java.lang.String getHighPrice() {
        java.lang.Object ref = highPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            highPrice_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string highPrice = 12;</code>
       */
      public com.google.protobuf.ByteString
          getHighPriceBytes() {
        java.lang.Object ref = highPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          highPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string highPrice = 12;</code>
       */
      public Builder setHighPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        highPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string highPrice = 12;</code>
       */
      public Builder clearHighPrice() {
        bitField0_ = (bitField0_ & ~0x00000800);
        highPrice_ = getDefaultInstance().getHighPrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string highPrice = 12;</code>
       */
      public Builder setHighPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        highPrice_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lowPrice_ = "";
      /**
       * <code>optional string lowPrice = 13;</code>
       */
      public boolean hasLowPrice() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string lowPrice = 13;</code>
       */
      public java.lang.String getLowPrice() {
        java.lang.Object ref = lowPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lowPrice_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lowPrice = 13;</code>
       */
      public com.google.protobuf.ByteString
          getLowPriceBytes() {
        java.lang.Object ref = lowPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lowPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lowPrice = 13;</code>
       */
      public Builder setLowPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        lowPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lowPrice = 13;</code>
       */
      public Builder clearLowPrice() {
        bitField0_ = (bitField0_ & ~0x00001000);
        lowPrice_ = getDefaultInstance().getLowPrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lowPrice = 13;</code>
       */
      public Builder setLowPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        lowPrice_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object closePrice_ = "";
      /**
       * <code>optional string closePrice = 14;</code>
       */
      public boolean hasClosePrice() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional string closePrice = 14;</code>
       */
      public java.lang.String getClosePrice() {
        java.lang.Object ref = closePrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            closePrice_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string closePrice = 14;</code>
       */
      public com.google.protobuf.ByteString
          getClosePriceBytes() {
        java.lang.Object ref = closePrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          closePrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string closePrice = 14;</code>
       */
      public Builder setClosePrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        closePrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string closePrice = 14;</code>
       */
      public Builder clearClosePrice() {
        bitField0_ = (bitField0_ & ~0x00002000);
        closePrice_ = getDefaultInstance().getClosePrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string closePrice = 14;</code>
       */
      public Builder setClosePriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        closePrice_ = value;
        onChanged();
        return this;
      }

      private long volume_ ;
      /**
       * <code>optional int64 volume = 15;</code>
       */
      public boolean hasVolume() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int64 volume = 15;</code>
       */
      public long getVolume() {
        return volume_;
      }
      /**
       * <code>optional int64 volume = 15;</code>
       */
      public Builder setVolume(long value) {
        bitField0_ |= 0x00004000;
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 volume = 15;</code>
       */
      public Builder clearVolume() {
        bitField0_ = (bitField0_ & ~0x00004000);
        volume_ = 0L;
        onChanged();
        return this;
      }

      private long totalVolume_ ;
      /**
       * <code>optional int64 totalVolume = 16;</code>
       */
      public boolean hasTotalVolume() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional int64 totalVolume = 16;</code>
       */
      public long getTotalVolume() {
        return totalVolume_;
      }
      /**
       * <code>optional int64 totalVolume = 16;</code>
       */
      public Builder setTotalVolume(long value) {
        bitField0_ |= 0x00008000;
        totalVolume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 totalVolume = 16;</code>
       */
      public Builder clearTotalVolume() {
        bitField0_ = (bitField0_ & ~0x00008000);
        totalVolume_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FuturesQuoteDataBase)
    }

    // @@protoc_insertion_point(class_scope:FuturesQuoteDataBase)
    private static final com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase();
    }

    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FuturesQuoteDataBase>
        PARSER = new com.google.protobuf.AbstractParser<FuturesQuoteDataBase>() {
      public FuturesQuoteDataBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FuturesQuoteDataBase(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FuturesQuoteDataBase> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FuturesQuoteDataBase> getParserForType() {
      return PARSER;
    }

    public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FuturesQuoteDataBase_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FuturesQuoteDataBase_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026FuturesQuoteData.proto\032\rCommand.proto\"" +
      "\304\002\n\024FuturesQuoteDataBase\022\031\n\003cmd\030\001 \002(\0162\014." +
      "CommandType\022\014\n\004time\030\002 \001(\t\022\023\n\013commodityNo" +
      "\030\003 \001(\t\022\022\n\ncontractNo\030\004 \001(\t\022\020\n\010bidPrice\030\005" +
      " \001(\t\022\017\n\007bidSize\030\006 \001(\003\022\020\n\010askPrice\030\007 \001(\t\022" +
      "\017\n\007askSize\030\010 \001(\003\022\021\n\tlastPrice\030\t \001(\t\022\020\n\010l" +
      "astSize\030\n \001(\003\022\021\n\topenPrice\030\013 \001(\t\022\021\n\thigh" +
      "Price\030\014 \001(\t\022\020\n\010lowPrice\030\r \001(\t\022\022\n\nclosePr" +
      "ice\030\016 \001(\t\022\016\n\006volume\030\017 \001(\003\022\023\n\013totalVolume" +
      "\030\020 \001(\003BJ\n6com.waben.stock.futuresgateway",
      ".yisheng.common.protobufB\020FuturesQuoteDa" +
      "ta"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.getDescriptor(),
        }, assigner);
    internal_static_FuturesQuoteDataBase_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FuturesQuoteDataBase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FuturesQuoteDataBase_descriptor,
        new java.lang.String[] { "Cmd", "Time", "CommodityNo", "ContractNo", "BidPrice", "BidSize", "AskPrice", "AskSize", "LastPrice", "LastSize", "OpenPrice", "HighPrice", "LowPrice", "ClosePrice", "Volume", "TotalVolume", });
    com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
