server:
  port: 8080
  context-path: /risk
spring:
  devtools:
    restart:
      additional-paths: risk/src/main/java
  mvc:
    throw-exception-if-no-handler-found: true
  rabbitmq:
    port: 5672
    host: 10.0.0.38
    username: yuyidi
    password: yuyidi
