server:
  port: 8082
  context-path: /operation
management:
  port: 3032
  context-path: /turbine
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false
fileSystem : http://10.0.0.31/
uploadFilePath : E:/upload/file/