server:
  port: 8002
  context-path: /operation
  tomcat:
    uri-encoding: UTF-8
logging:
  config: classpath:log/logback.xml
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: @active@
  devtools:
    restart:
      enabled: true
      additional-paths: applayer/operation/src/main/java
