server:
  port: 8085
  context-path: /promotion
  connection-timeout: 60000
management:
  port: 3035
  context-path: /turbine
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
feign:
  hystrix:
    enabled: false
hystrix:
  command:
    default:
     execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 500
      queueSizeRejectionThreshold: 300
ribbon:
  OkToRetryOnAllOperations: false
  ReadTimeout: 40000
  ConnectTimeout: 40000