server:
  port: 8009
  tomcat:
    max-threads: 500
management:
  port: 3009
  context-path: /trubine
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          connection:
            autocommit: true
feign:
  hystrix:
    enabled: false
hystrix:
  command:
    default:
     execution:
        isolation:
          strategy: THREAD
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            timeoutInMilliseconds: 10000
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 500
      queueSizeRejectionThreshold: 300
ribbon:
  OkToRetryOnAllOperations: false
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
needquotetask: true