server:
  port: 8003
  context-path: /strategy
spring:
  devtools:
    restart:
      additional-paths: datalayer/strategy/src/main/java
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          connection:
            autocommit: true