logging:
  config: classpath:log/logback.xml
eureka:
  instance:
      prefer-ip-address: false
      metadata-map:
        cluser: prontera
        management:
          port: ${management.port}
          context-path: ${management.context-path}
        health:
          path: ${management.context-path}/health
      healthCheckUrlPath: ${management.context-path}/health
      statusPageUrlPath: ${management.context-path}/info
#      instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: false
spring:
  application:
    name: discovery