server:
  port: 8887
  context-path: /discovery
spring:
  devtools:
    restart:
      additional-paths: discovery/src/main/java
logging:
  config: classpath:log/logback.xml
eureka:
  instance:
      healthCheckUrlPath: ${server.context-path}/health
      statusPageUrlPath: ${server.context-path}/info
      hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/discovery/eureka/