logging:
  config: classpath:log/logback.xml
eureka:
  instance:
      prefer-ip-address: true
      metadata-map:
        cluser: finance
        management:
          port: ${management.port}
          context-path: ${management.context-path}
        health:
          path: ${management.context-path}/health
      healthCheckUrlPath: ${management.context-path}/health
      statusPageUrlPath: ${management.context-path}/info
      hostname: ${spring.cloud.client.ipAddress}
      lease-expiration-duration-in-seconds: 30  # 续约到期时间
      lease-renewal-interval-in-seconds: 10  #续约更新时间间隔
  client:
    register-with-eureka: true
    fetch-registry: true
  server:
    renewal-percent-threshold: '0.8'
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
