logging:
  config: classpath:log/logback.xml
eureka:
  instance:
      prefer-ip-address: true
      metadata-map:
        cluser: finance
        management:
          port: ${management.port}
          context-path: ${management.context-path}
        health:
          path: ${management.context-path}/health
      healthCheckUrlPath: ${management.context-path}/health
      statusPageUrlPath: ${management.context-path}/info
      hostname: ${spring.cloud.client.ipAddress}
  client:
    register-with-eureka: true
    fetch-registry: true
  server:
    renewal-percent-threshold: '0.8'
